hw2
vanyusha82228/Tin_SPR pull request #2
Opened 2024-02-25 10:25 UTC by vanyusha82228

2024-03-04 13:19 UTC, x1vr64 requested changes
В целом хорошо, но сейчас coverage нету, потому что он не может запустить тесты. Ошибка `this.wireMockServer is null` это не основная ошибка, это следствие неправльно настроенного теста. 

https://wiremock.org/docs/junit-jupiter/ Вот ссылка, где можно почитать, как настроить с junit5.

Надо починить тесты

2024-03-04 13:19 UTC, x1vr64 commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +@Validated @Configuration public class ClientConfiguration {
В целом аннотации можно сверху писать. Необязательно все в одну строчку делать. Сейчас неудобно это читается

2024-03-04 13:19 UTC, x1vr64 commented on scrapper/src/main/java/edu/java/dto/GitHubRepositoryDTO.java
> +    private OffsetDateTime updatedAt;
У тебя были вопросы, про то, почему не заполняется updatedAt. А у stackoverflow такой же ответ в датах? Насколько я знаю, там разные форматы даты, при этом мы их оба десериализуем в `OffsetDateTime` Смотри в сторону настроек десерриализации и как это работает. (Проще написать тесты на оба клиента и пробовать уже настраивать webclient или dto на работу с определенным api)

2024-03-04 13:19 UTC, x1vr64 commented on scrapper/src/main/java/edu/java/scheduler/LinkUpdaterScheduler.java
> +        }
Можно это отсюда пока убрать

2024-03-04 13:19 UTC, x1vr64 commented on scrapper/src/test/java/edu/java/scrapper/GitHubWebClientTest.java
> +    @Rule
`@Rule` и `@ExtendWith` относятся к разным версиям тестового фреймворка. 4 и 5 соответственно. Не стоит их мешать сразу. Посмотри, как запустить wiremock с junit5

2024-03-04 13:19 UTC, x1vr64 commented on scrapper/src/test/java/edu/java/scrapper/GitHubWebClientTest.java
> +public class GitHubWebClientTest {
Не забудь сделать тест для Stackoverflow

2024-03-04 13:19 UTC, x1vr64 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> -public abstract class IntegrationTest {
В будущем он тебе пригодиться. Я бы его пока что не удалял

2024-03-04 13:19 UTC, x1vr64 commented on scrapper/src/test/resources/mappings/github_repository.json
> +{
А этот файл где-то используется?

2024-03-04 16:06 UTC, vanyusha82228 commented on scrapper/src/test/resources/mappings/github_repository.json
> +{
я это хотел использовать для тестов но не получилось...

2024-03-04 16:07 UTC, vanyusha82228 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> -public abstract class IntegrationTest {
просто его сначала не было а потом он появился и я не понял что это и зачем вот и решил удалить

2024-03-04 16:09 UTC, vanyusha82228 commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +@Validated @Configuration public class ClientConfiguration {
а я даже не знаю как это получилось..
вроде делал сверху вниз и все ок было
может как-то автоформатирование это само сделало

2024-03-04 16:10 UTC, vanyusha82228 commented on scrapper/src/main/java/edu/java/scheduler/LinkUpdaterScheduler.java
> +        }
Просто надо было как-то запустить и проверить работу вот и решил попробовать временно так

2024-03-04 16:12 UTC, vanyusha82228 commented on scrapper/src/test/java/edu/java/scrapper/GitHubWebClientTest.java
> +public class GitHubWebClientTest {
я просто всё пробовал сначала на гитхаб клиенте

2024-03-08 15:21 UTC, vanyusha82228 commented on scrapper/src/main/java/edu/java/dto/GitHubRepositoryDTO.java
> +    private OffsetDateTime updatedAt;
Пофиксил тесты стало понятно что не так
там по времени не было смещения под местно время
и посмотри пожалуйста правильно всё ли я это сделал
довольно долго разбирался со временем, ну переводом времени

2024-03-08 15:31 UTC, vanyusha82228 commented
Привет! вроде все правки внес но почему-то я не понимаю не проходит билд хотя вроде же у меня всё норм
вот
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/9c7b1a95-1e41-4a47-af62-b2308d7eabfc)


и все тесты проходят и там коректные данные вроде все те которые нужны

2024-03-08 15:41 UTC, vanyusha82228 commented
Написание тестов действительно помогло разобраться с этими датами!(ну если конечно я правильно всё сделал))

Так же я это реализовал всё уже в третьем пр
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/58073476-6a16-4960-8990-19555b91d65d)

там код кавердж показывается
но есть ньюанс с этим телеграмм токеном
я изучил статью и вот пытался сделать как там 
но не получается... я впрада не знаю почему.. 
делал вот так 
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/3086ba10-a629-4e36-868b-ac5bfa973dda)
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/e22a648f-7697-4333-bbb3-b5033761c280)

и ещё как я пытался делать ещё давно 
Как писали люди в чате тоже не получалось 
там они заходили вот сюда
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/768ff810-5515-42e5-8716-caf5b566d8b5)

и туда добавляли токен
я делал так же он не получалось

2024-03-08 15:43 UTC, vanyusha82228 commented
Произошло что-то странное)
Я сейчас попробовал запустить бота и всё заработало..
то есть нет вот этого
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/6eaf316a-aef7-4e26-a032-0b8fed7c96ee)

2024-03-08 15:52 UTC, vanyusha82228 commented
А ещё вспомнил 
по поводу @Scheduled 
Я когда только первый раз делал пробовал .toMillis() я в интернете находил что это должно помочь 
но не помогло поэтому 100000
везде было написано что  toMillis() поможет но почему-то в моём случае нет
Можешь подсказать почему у меня это не получается?

2024-03-09 10:24 UTC, x1vr64 commented on scrapper/src/main/java/edu/java/dto/GitHubRepositoryDTO.java
> +    private OffsetDateTime updatedAt;
Смотри, проблема в том, что когда ты в тесте создаешь ответ мока (В тестах, когда мы проверяем, что наши клиенты работают корректно) мы можем допустить баги при создании ответа. Например. Если взять апи stackoferflow, можно увидеть, что они отправляют дату в формате epochSeconds, но в нашем тесте мы записываем полностью дату.

Возьми полностью ответ с их сайта (https://api.stackexchange.com/docs/questions-by-ids#order=desc&sort=activity&ids=78131948&filter=default&site=stackoverflow&run=true) и используй его в нашем тесте

2024-03-09 10:28 UTC, x1vr64 commented
> Привет! вроде все правки внес но почему-то я не понимаю не проходит билд хотя вроде же у меня всё норм

Там да, проблемы с тестовой датой. Лучше использовать конечно настоящий ответ сервиса, при проверке клиента. Также можно проверять offsetDateTime через `assertTrue(date.isEqual(date2))`, т.к. по сути, эти даты обозначают одно и то же время, пусть и с разным смещением

2024-03-09 11:12 UTC, x1vr64 commented
> А ещё вспомнил по поводу @scheduled Я когда только первый раз делал пробовал .toMillis() я в интернете находил что это должно помочь но не помогло поэтому 100000 везде было написано что toMillis() поможет но почему-то в моём случае нет Можешь подсказать почему у меня это не получается?

Смотри, в документации к `@Scheduled#fixedDelayString` написано `This attribute variant supports Spring-style "${...}" placeholders as well as SpEL expressions` т.е. поддерживает **оба** варианта написания. Т.е. вариант через доллар, это вытаскивание из настроек приложения https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/value-annotations.html#page-title, а SpEl это написание через `#{}` и описан вот тут https://docs.spring.io/spring-framework/reference/core/expressions.html.

Чтобы работал `.toMillis()` надо писать через SpEl. Спел может получать значения из контекста по названию бина (https://docs.spring.io/spring-framework/reference/core/expressions/language-ref/bean-references.html).  Можно поставить `@Bean` над Scheduled, как то так

```java
public record ApplicationConfig(
    @NotNull
    @Bean
    Scheduler scheduler,
){}
```

И потом написать в строке шедулера `#{@scheduler.interval.toMillis()}`

2024-03-09 11:15 UTC, x1vr64 commented
Давай разберемся с вебклиентом. Будем использовать настоящий ответ от гитхаба и стэковерфлоу в тесте

2024-03-10 10:29 UTC, vanyusha82228 commented
Привет! Сделал тесты с использованием настоящих данных! И вот понял что для стак оверфлоу надо дополнительное дто(так как там данные лежат в items). Это поправил и теперь работает как и должно.(ну я так думаю))

2024-03-10 10:31 UTC, vanyusha82228 commented
> > А ещё вспомнил по поводу @scheduled Я когда только первый раз делал пробовал .toMillis() я в интернете находил что это должно помочь но не помогло поэтому 100000 везде было написано что toMillis() поможет но почему-то в моём случае нет Можешь подсказать почему у меня это не получается?
> 
> Смотри, в документации к `@Scheduled#fixedDelayString` написано `This attribute variant supports Spring-style "${...}" placeholders as well as SpEL expressions` т.е. поддерживает **оба** варианта написания. Т.е. вариант через доллар, это вытаскивание из настроек приложения https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/value-annotations.html#page-title, а SpEl это написание через `#{}` и описан вот тут https://docs.spring.io/spring-framework/reference/core/expressions.html.
> 
> Чтобы работал `.toMillis()` надо писать через SpEl. Спел может получать значения из контекста по названию бина (https://docs.spring.io/spring-framework/reference/core/expressions/language-ref/bean-references.html). Можно поставить `@Bean` над Scheduled, как то так
> 
> ```java
> public record ApplicationConfig(
>     @NotNull
>     @Bean
>     Scheduler scheduler,
> ){}
> ```
> 
> И потом написать в строке шедулера `#{@scheduler.interval.toMillis()}`

что-то тупанул я.. почему-то я в упор не мог разгялдеть различия # и $

2024-03-10 12:26 UTC, x1vr64 approved these changes

2024-03-10 13:00 UTC, merged