hm4
vanyusha82228/Tin_SPR pull request #4
Opened 2024-03-18 11:13 UTC by vanyusha82228

2024-03-18 11:14 UTC, vanyusha82228 commented
Правки в тесты можно будет внести после добавления реализации?

2024-03-19 09:06 UTC, vanyusha82228 commented
Привет! Можешь подсказать правильно ли я бд сделал? Может что надо добавить, или убрать или может таблицу какую-нибудь ещё добавить?
А правильно ли я понял что не надо много таблиц создавать в одном sql скрипте? А то я по пробовал не получилось
Правильно ли я понял 4 задание? Вроде вот интеграционный тест проходит оно там возникает ошибка вот
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/bf5e6726-01ff-478c-9c88-76998f8388b0)

2024-03-31 10:04 UTC, x1vr64 requested changes
Привет!)
Хорошая идея, с использованием бота в разных чатах!)

Давай только, пока остановимся с вариантом, когда мы в личке бота вызываем бота. Просто если и правда, попробовать реализовать идею, на проект уйдет больше времени (т.к. проект рассчитан на такую схему, чтобы мы все успели)

2024-03-31 10:04 UTC, x1vr64 commented on migrations/01_create_user_table.sql
> +CREATE TABLE "user" (
Смотри, в терминологии liquibase есть такое понятие, как changeset. В нем обычно указывается автор изменений, в рамках чего мы добавили эти изменения итд. Нужно указывать эту информацию, т.к. сейчас все подписывается как 'raw'

2024-03-31 10:04 UTC, x1vr64 commented on migrations/01_create_user_table.sql
> +    id SERIAL PRIMARY KEY,
В целом, 2ккк ключей в рамках учебного проекта хватит, но думаю не стоит экономить на первичном ключе) Когда-то, программисты прошлого сталкивались с этой проблемой. Мы же в целом вообще не хотим об этом думать, так что лучше использовать bigserial

2024-03-31 10:04 UTC, x1vr64 commented on migrations/01_create_user_table.sql
> +    telegram_id BIGINT NOT NULL UNIQUE,
Смотри, идея хорошая, сделать нашего бота, способным отслеживать ссылки разных пользователей, в рамках одного чата (Если я правильно понимаю, что телеграм может отдать несколько разных id, чата и пользователя, в рамках одного сообщения), но сейчас у схемы есть недостаток. 
Пользователь может отслеживать ссылки в рамках только одного чата (т.е. telegram_id unique, а chat_id обязательное поле), что ломает нашу задумку(

2024-03-31 10:04 UTC, x1vr64 commented on migrations/03_create_link_table.sql
> +    user_id BIGINT NOT NULL,
Сейчас одна и та же ссылка, будет дублироваться для каждого пользователя, т.к. идентификатор пользователя "зашит" в ссылке. С этим подходом будут проблемы, т.к. мы одну и ту же ссылку будем сканировать каждый раз, для каждого пользователя. (Делать усложнения кода, для обработки такого поведения кажется не слишком обоснованным, т.к. логичнее делать это один раз, а не делать промежуточные структуры данных, для отслеживания проверенных ссылок в обработчике).

Давай сделаем тут промежуточную таблицу для связи между пользователем и ссылкой. так наша схема будет лучше ложиться на нашу задачу.

(Подход, когда данные денормализуются, имеет место быть, однако у нас не такой случай)

2024-03-31 10:04 UTC, x1vr64 commented on migrations/05_create_resource_table.sql
> +CREATE TABLE resource (
Как я понимаю, ресурс, это разделение github, stackoverflow итд. При создании таблицы, можно добавлять комментарии к колонкам и таблицам, чтобы дать больше информации. (Также, ребята которые отвечают за документацию, тебе будут очень благодарны за это :) )

2024-03-31 10:04 UTC, x1vr64 commented on migrations/06_add_resource_id_column_to_link.sql
> +    ADD COLUMN resource_id BIGINT,
Если это и правда тип ссылки, то мы же всегда будем знать о его типе. Давай сюда поставим not null ограничение?

P.S. Если были проблемы, с добавлением notnull, т.к. старые данные его не имеют, то стоит написать скрипт миграции, которые проставят нужные данные. (Т.к. у нас тестовая бд, и мр еще не в мастере, можно также поправить схему в ченджоге).

Другой подход, добавить новое значение ресурса, как неизвестного и обработать (понять, что за ссылка) можно будет уже в коде и обновить, в случае чего)

2024-03-31 10:04 UTC, x1vr64 commented on migrations/master.xml
> +</databaseChangeLog>
Тут, окей, что держишь файлы миграции рядом с мастером. Однако по опыту больших проектов, не хочется чтобы в одной директории было много файлов (когда миграций станет много). Команды начинают разделять миграции по годам (версиям итд), чтобы внести порядок и не перегружать голову)

2024-03-31 10:04 UTC, x1vr64 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            Liquibase liquibase = new Liquibase("F:\\TinkoffSpring\\migrations\\master.xml", new FileSystemResourceAccessor(), database);
Смотри, путь до файла миграции отличается для каждой машины. Например, я сижу с linux машины, у меня разделитель директории это `/`. 
Как вариант решения данной проблемы, есть в задании:
 - Текущий каталог -- new File("."), но работать с каталогами удобнее через new File(".").toPath()
 - Path позволяет легко подняться на уровень выше (parent), для перемещения "вниз" можно использовать метод resolve.

Попробуй через данные подсказки, добраться из текущего каталога (проекта scrapper), дойти до родительского, а затем уже в папку миграции

2024-03-31 10:05 UTC, x1vr64 commented
> Правки в тесты можно будет внести после добавления реализации?

Да, как тебе удобно) В целом можно отдельный мр с тестами сделать

2024-03-31 10:07 UTC, x1vr64 commented
>  А правильно ли я понял что не надо много таблиц создавать в одном sql скрипте? А то я по пробовал не получилось

Можно добавлять несколько таблиц в рамках одного ченджсета (скрипта). Можешь написать, что именно не получилось?

2024-04-02 11:25 UTC, vanyusha82228 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            Liquibase liquibase = new Liquibase("F:\\TinkoffSpring\\migrations\\master.xml", new FileSystemResourceAccessor(), database);
Теперь то что нужно, да?
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/54dd124d-ab34-494c-8d46-79771fc1abc6)

2024-04-02 11:26 UTC, vanyusha82228 commented
> > А правильно ли я понял что не надо много таблиц создавать в одном sql скрипте? А то я по пробовал не получилось
> 
> Можно добавлять несколько таблиц в рамках одного ченджсета (скрипта). Можешь написать, что именно не получилось?

я вот так в одном скрипте хотел сделать но не получалось чего-то
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/37d2543e-4a71-41b8-bf42-ae91ef4e4e04)

2024-04-02 11:28 UTC, vanyusha82228 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            Liquibase liquibase = new Liquibase("F:\\TinkoffSpring\\migrations\\master.xml", new FileSystemResourceAccessor(), database);
я там я ещё подключение в трай виз ресурсес добавил наверно так же правильней будет
а то что-то я сразу забыл так сделать

2024-04-02 11:33 UTC, vanyusha82228 commented
> > Правки в тесты можно будет внести после добавления реализации?
> 
> Да, как тебе удобно) В целом можно отдельный мр с тестами сделать

А можешь, пожалуйста, подсказать какие тесты можно написать ещё( для каких классов, методов)?
а то мне не нравится ещё мой маленький процент прокрытия
Наверно же на работе требуют чтобы он был побольше чем вот например в моей работе это

2024-04-02 12:25 UTC, vanyusha82228 commented on migrations/01_create_user_table.sql
> +    telegram_id BIGINT NOT NULL UNIQUE,
Вообще telegram_id это id человека в телеграмме  
там же у  каждого человека свой уникальный айдишник

2024-04-02 12:33 UTC, vanyusha82228 commented on migrations/01_create_user_table.sql
> +    telegram_id BIGINT NOT NULL UNIQUE,
Вообще я думал что вот telegram_id это айдишник человека в телеграмме он же вроде у всех есть а вот username не у всех поэтому я решил добавить так

2024-04-02 12:33 UTC, vanyusha82228 commented on migrations/01_create_user_table.sql
> +    telegram_id BIGINT NOT NULL UNIQUE,
ну наверно это так

2024-04-02 12:35 UTC, vanyusha82228 commented on migrations/03_create_link_table.sql
> +    user_id BIGINT NOT NULL,
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/445c7d2c-9d22-4d15-84a1-c87062a951ce)

ну вот так у меня в вобщем выглядит схема
это ок или что-т не так

2024-04-02 12:36 UTC, vanyusha82228 commented on migrations/master.xml
> +</databaseChangeLog>
теперь в таблице вот так
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/beb65baf-bf44-4362-8a86-89c4b351911f)
так же требуется?

2024-04-02 12:37 UTC, vanyusha82228 commented on migrations/01_create_user_table.sql
> +CREATE TABLE "user" (
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/707fb9f8-f4bd-42bc-a2b8-ab563c3ac33b)
вот так требуется делать?

2024-04-02 12:38 UTC, vanyusha82228 commented on migrations/master.xml
> +</databaseChangeLog>
Надо sql скрипты в отдельную папочку сложить?

2024-04-02 13:30 UTC, vanyusha82228 commented on migrations/master.xml
> +</databaseChangeLog>
вот так вот?
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/3f19a032-7af7-4b68-a85f-1a92379f8e9f)

2024-04-02 13:37 UTC, vanyusha82228 commented on migrations/05_create_resource_table.sql
> +CREATE TABLE resource (
добавил просто комментарии
так ок?)

2024-04-02 13:38 UTC, vanyusha82228 commented on migrations/05_create_resource_table.sql
> +CREATE TABLE resource (
Пробовал ещё COMMENT но почему то не сработало
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/e6a483c4-9905-4c06-9b63-76300e503ca8)

2024-04-18 09:42 UTC, vanyusha82228 commented
можно пожалуйста коментариев про вот этот коммит
[hw 5 task2](https://github.com/vanyusha82228/Tin_SPR/pull/4/commits/c1ed243aa291475c7637ffbb9c0de324a0228193)
правильно ли я вот так сделал?
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/ad132934-9a86-4edb-9fbe-6b5ac55284d7)

правильно ли я понял что JdbcLinkService и JdbcTgChatService должны взаимодействовать с дао которые мы делали на прошлом шаге?

Где должен находится interface LinkUpdater? не понимаю доконца 

и вот контролеры подскажите пожалуйста что с ними надо делать? скорее всего я что-то не то делаю

2024-04-18 10:03 UTC, vanyusha82228 commented
я в 3 задание не много не понимаю как это должно работать с прослушиванием обновлений
[w 5 task3](https://github.com/vanyusha82228/Tin_SPR/pull/4/commits/0b4b54e1dc70f2c07c136dd2587d35430874da70)

если вот BotWebClient находится в модуле Bot

2024-04-22 10:41 UTC, vanyusha82228 commented
@x1vr64

2024-04-24 14:53 UTC, Vladislav-Kisliy commented
Добрый день, меня прислали разгребать завалы по ДЗ-кам, подскажите какие вопросы для вас еще актуальны?

2024-04-24 14:56 UTC, Vladislav-Kisliy reviewed
нужна пара мелких доработок

2024-04-24 14:56 UTC, Vladislav-Kisliy commented on scrapper/src/main/java/edu/java/domain/dao/UserDao.java
> +        return null;
надо страться не возвращать `null`, тем более когда тут есть лист. Возвращайте пустой список

2024-04-24 14:56 UTC, Vladislav-Kisliy commented on scrapper/src/test/java/edu/java/scrapper/IntegrationEnvironmentTest.java
> +        assertTrue(POSTGRES.isRunning());
по тестам я бы добавил проверки, что ваши миграции все-таки накатились на БД

2024-04-24 15:10 UTC, vanyusha82228 commented on scrapper/src/main/java/edu/java/domain/dao/UserDao.java
> +        return null;
Добрый день! просто забыл сделать сейчас там загружу изменения 

я если что в этом пр две домашке 
Можете пожалуйста сказать что так или не так по 4ой или всё норм
а чуть позже я напишу вопросы по 5ой. Хорошо?
а дальше по мере проверок буду отдельные пр открывать 
просто давно не проверяли я решил 5 делать в 4ом пре

2024-04-24 15:17 UTC, vanyusha82228 commented
Да те вопросы которые я писал актуальны

2024-04-24 15:39 UTC, vanyusha82228 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationEnvironmentTest.java
> +        assertTrue(POSTGRES.isRunning());
вроде сделал 
можете проверить пожалуйста
правильно ли я вам понял что надо
[add test migr](https://github.com/vanyusha82228/Tin_SPR/pull/4/commits/54fec4c0d6b07f25cd1aa054caab1b8e56e7ea87)

2024-04-24 15:44 UTC, vanyusha82228 commented
По пятому задания 
я сделал
1. Описал таблицы бд в папке domain model
2. Сделал дао
 дальше я описал вроде что не получается и не понимаю и в тупике я..

2024-04-24 16:02 UTC, vanyusha82228 commented
> Добрый день, меня прислали разгребать завалы по ДЗ-кам, подскажите какие вопросы для вас еще актуальны?

и там там такая ситуация была я Александру ее описывал почему не мог делать дз и мне говорили не переживать и делать в своём темпе, но так как проверки домашек затянулись и я не мог делать дальше, поэтому следующих нет
но я готов оперативно их делать и скидывать

2024-04-24 16:05 UTC, vanyusha82228 commented
> > Добрый день, меня прислали разгребать завалы по ДЗ-кам, подскажите какие вопросы для вас еще актуальны?
> 
> и там там такая ситуация была личного характера. Я Александру ее описывал почему не мог делать дз и мне говорили не переживать и делать в своём темпе, но так как проверки домашек затянулись и я не мог делать дальше, поэтому следующих нет но я готов оперативно их делать и скидывать

2024-04-24 20:06 UTC, Vladislav-Kisliy commented
давай тогда так, я засчитаю 4ое задание и в 5м пришлешь мне ссылку на этот же МР. И дальше продолжим, ок?

В общем возвращай 4ое, на проверку

2024-04-24 20:10 UTC, Vladislav-Kisliy commented
> > > Добрый день, меня прислали разгребать завалы по ДЗ-кам, подскажите какие вопросы для вас еще актуальны?
> > 
> > 
> > и там там такая ситуация была личного характера. Я Александру ее описывал почему не мог делать дз и мне говорили не переживать и делать в своём темпе, но так как проверки домашек затянулись и я не мог делать дальше, поэтому следующих нет но я готов оперативно их делать и скидывать

не волнуйся, все завалы разберем, было бы желание

2024-04-24 20:13 UTC, vanyusha82228 commented
> давай тогда так, я засчитаю 4ое задание и в 5м пришлешь мне ссылку на этот же МР. И дальше продолжим, ок?
> 
> 
> 
> В общем возвращай 4ое, на проверку

Если с 4ым все хорошо и не надо дорабатывать можно и закрыть
На платформе уже нажимал закрывать дз и присылал ссылку на этот мр

2024-04-24 20:16 UTC, vanyusha82228 commented
> > > > Добрый день, меня прислали разгребать завалы по ДЗ-кам, подскажите какие вопросы для вас еще актуальны?
> 
> > > 
> 
> > > 
> 
> > > и там там такая ситуация была личного характера. Я Александру ее описывал почему не мог делать дз и мне говорили не переживать и делать в своём темпе, но так как проверки домашек затянулись и я не мог делать дальше, поэтому следующих нет но я готов оперативно их делать и скидывать
> 
> 
> 
> не волнуйся, все завалы разберем, было бы желание


Да желание конечно есть! Очень хочется учиться и завершить этот проект

2024-04-25 11:13 UTC, Vladislav-Kisliy commented on scrapper/src/main/java/edu/java/domain/dao/ChatDao.java
> +public class ChatDao implements GenericDao<Chat> {
DAO это слишком общее название, если привязывать это к спрингу, то это обычно Repository классы. Поэтому желательно классы переименовать, к виду ChatRepository

FYI https://stackoverflow.com/questions/42334096/spring-repository-annotation-for-dao

тут же попробую ответить на вопросы, общая архитектура такая
controller'ы - классы которые принимают запросы от клиентов по HTTP, надо стараться их делать как можно проще и не добавлять бизнесс логику на этот слой
repository - классы для работы с хранилищами данных. Подход такой же, там должен быть код только связанный с базой и не больше
service - связывает 2е слоя описанных выше и место для бизнес-логики. Берет данные из репозиториев, что-то с ними делает и отдает клиентам, либо наоборот получает от контроллеров данные и передает данные в репозитории для сох-я.

Если что-то осталось непонятным, пиши

2024-04-25 17:23 UTC, vanyusha82228 commented
Здравствуйте! Понял про архитектуру!
Переименовал их в репозитории
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/decff340-17f3-45c8-afe9-de1295e87454)

в некоторые из них добавил пару методов, по поиску элементов, можете посмотреть на них пожалуйста

Может те пожалуйста глянуть в тот раздел где сервисы я просто не понимаю правильно ли я их реализую 
допустим вот этот
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/69390592-9606-4365-8f98-f150f7b66121)
я брал интерсфейсы из задания и
Там раньше было в интерфейсе Link я его заменил на void? Правильное ли решение
наверно подразумевалось что у меня в таблице Link будут все данные
но у меня база данных спроктирована по другому наверно не так как хотелось

и у меня таблица связывающая чат и ссылки получается вот
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/624b3ef5-31b8-405b-a8f2-67d7e2f721ed)

правильно ли я двигаюсь в реализации JdbcLinkService

и  у меня закрадывается мысль может бд надо как-то по другому переделать?

Вопрос по этому интерфейсу
![Uploading image.png…]()

у нему надо написать реализацию которая каким-то образом проверяла обновления ссылки в бд? а потом его использовать в шедуулере?

2024-04-25 17:43 UTC, vanyusha82228 commented
а ещё я попробовал написать тест для LinkRepository и он у меня не проходит писало что-то типа того что не находит master.xml хотя же предыдущие тесты где он нужен был всё работало
не понимаю пока что в чем проблема

2024-04-26 13:22 UTC, Vladislav-Kisliy reviewed
Все вроде правильно расположено, давайте добьем мелкие правки и будем переходить к след-му заданию

2024-04-26 13:22 UTC, Vladislav-Kisliy commented on scrapper/src/main/java/edu/java/domain/jdbc/JdbcLinkService.java
> +        userLink.setLinkId(link.getId());
надо понимать, что всякие архитектуры и умные книжки это не догма потому как все кейсы они не могут охватить, и на самом деле они и не пытаются. Надо же смотреть на код с точки зрения практичности и быстродействия. Вам БД предоставляется возможность джойнить таблицы и получать результат одним запросом. По моему надо этим пользоваться

2024-04-26 13:22 UTC, Vladislav-Kisliy commented on scrapper/src/main/java/edu/java/domain/jdbc/JdbcLinkService.java
> +
+

2024-04-26 13:22 UTC, Vladislav-Kisliy commented on scrapper/src/main/java/edu/java/domain/jdbcInterface/LinkService.java
> +    void remove(long tgChatId, URI url);
лично я, стараюсь избегать методов void где только могу, по одной простой причине - их сложно тестировать. Кроме того, в такие методы люди пытаются запихнуть всю возможную логику, что тоже не очень хорошо. Поэтому если вы можете что-то адекватное наружу, то лучше это и возвращать. Например, add  может возвращать инстанс созданного класса, зачастую id генерируется на базе

2024-04-26 13:22 UTC, Vladislav-Kisliy commented on scrapper/src/main/java/edu/java/domain/repository/LinkRepository.java
> +        String query = String.format("select * from links where url = '%s'", url.toString());
вы же выше использовали preparedStatement, зачем тут через формат?

2024-04-26 13:22 UTC, Vladislav-Kisliy commented on scrapper/src/main/java/edu/java/domain/repository/ResourceRepository.java
> +            "SELECT * FROM resource",
в запросах лучше не использовать звездочки, таблица со временем может расшириться и БД будет больно вытаскивать не используемые поля

2024-04-26 13:22 UTC, Vladislav-Kisliy commented on scrapper/src/main/java/edu/java/domain/repository/UserRepository.java
> +            format("SELECT * FROM user JOIN chat ON \"user\".chat_id = chat.id WHERE chat.id = %d", chatId);
и тут тоже формат
для больших SQL запросов, удобно использовать "текстовые блоки". Это которые начинаются с `"""`

2024-04-26 13:22 UTC, Vladislav-Kisliy commented on scrapper/src/test/java/edu/java/scrapper/IntegrationEnvironmentTest.java
> +        assertTrue(POSTGRES.isRunning());
да, пойдет

2024-04-29 15:25 UTC, vanyusha82228 commented
не много не понимаю почему билд не проходит 
там написана вот package edu.java.bot.client does not exist
но всё же создано и есть

2024-04-29 15:40 UTC, vanyusha82228 commented
Не подскажите что тут надо сделать?
![image](https://github.com/vanyusha82228/Tin_SPR/assets/80487403/3749e4f9-5a3c-4d57-a568-f28f2b87f9fc)

Просто чтобы приложение работало?

2024-04-30 10:41 UTC, merged